### Data Structures Cont....

#### Dictionary:
* {} --- Dictionary
* key and values pair
* Dictionary is mutable
* Key should be unique.
* We can access elements from the dictionary using key.


In [3]:
a = {"fruits":["apple","banana","grapes"],
    "vegetables":["carrot","tomatoes","cabbage"],
    "Dryfruits":["cashew","Almond","pista"]}


In [2]:
type(a)

dict

In [4]:
a["fruits"]

['apple', 'banana', 'grapes']

In [5]:
a["fruits"][-1]

'grapes'

In [6]:
a = {"fruits":["apple","banana","grapes"],
    "vegetables":["carrot","tomatoes","cabbage"],
    "Dryfruits":["cashew","Almond","pista"],
    "fruits":"orange"}

In [7]:
a

{'fruits': 'orange',
 'vegetables': ['carrot', 'tomatoes', 'cabbage'],
 'Dryfruits': ['cashew', 'Almond', 'pista']}

In [10]:
a.keys()

dict_keys(['fruits', 'vegetables', 'Dryfruits'])

In [11]:
a.values()

dict_values(['orange', ['carrot', 'tomatoes', 'cabbage'], ['cashew', 'Almond', 'pista']])

In [12]:
a.items()

dict_items([('fruits', 'orange'), ('vegetables', ['carrot', 'tomatoes', 'cabbage']), ('Dryfruits', ['cashew', 'Almond', 'pista'])])

In [13]:
help(dict)

Help on class dict in module builtins:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |  
 |  Methods defined here:
 |  
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __init__(self,

### Set

* Set makes all values unique.
* {}--set

In [14]:
a = {1,2,3,45}

In [15]:
type(a)

set

In [16]:
b = {1,2,3,4,4,3,2}

In [17]:
b

{1, 2, 3, 4}

In [18]:
help(set)

Help on class set in module builtins:

class set(object)
 |  set() -> new empty set object
 |  set(iterable) -> new set object
 |  
 |  Build an unordered collection of unique elements.
 |  
 |  Methods defined here:
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __contains__(...)
 |      x.__contains__(y) <==> y in x.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iand__(self, value, /)
 |      Return self&=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __ior__(self, value, /)
 |      Return self|=value.
 |  
 |  __isub__(self, value, /)
 |      Return self-=value.
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __ixor__(self, value, /)
 |      Re

### Functions:

* A function is a code which is to call every time when we required.


In [41]:
def sample(*a):
    print(a)
    
    

In [43]:
sample(14,13,15)

(14, 13, 15)


In [21]:
def sample1():
    print("Welcome")

In [22]:
sample1()

Welcome


In [27]:
def add(a,b):
    c = a+b
    return c

In [28]:
add(10,20)

30

In [44]:
def loop(a):
    for i in range(a):
        print(i)
    return
    

In [46]:
loop(5)

0
1
2
3
4


In [33]:
### return will always holds a single value
### print prints whatever we define in the statement.

## Numpy -- Numerical Python:

* Numpy is used to perform all mathematical and scientific calculations.


#### installation of numpy:

In [47]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


### importing :

In [48]:
import numpy as np

### Creating array:

#### 1-d array:

In [49]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [50]:
a.dtype

dtype('int32')

In [51]:
a = np.array([1,2,3,4,'a'])
a.dtype

dtype('<U11')

In [53]:
np.append(a,10)

array(['1', '2', '3', '4', 'a', '10'], dtype='<U11')

In [54]:
np.append(a,['ab',4,1])

array(['1', '2', '3', '4', 'a', 'ab', '4', '1'], dtype='<U11')

In [57]:
### creating array within a range:

a = np.arange(1,11,2)

In [58]:
a

array([1, 3, 5, 7, 9])

In [59]:
a.nbytes

20

In [60]:
a.itemsize

4

In [61]:
len(a)

5

In [62]:
a = np.linspace(1,10,20)

In [63]:
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [64]:
a = np.logspace(1,10,20)

In [65]:
a

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [66]:
np.full(5,'a')

array(['a', 'a', 'a', 'a', 'a'], dtype='<U1')

In [68]:
np.ones(10,dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [70]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [71]:
a.ndim

1

#### 2-d array:

* Combination of more 1-d array is 2-d array.


In [72]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
b.ndim

2

In [74]:
b.dtype

dtype('int32')

In [75]:
b.nbytes

32

In [76]:
b.itemsize

4

In [77]:
len(b)

2

In [78]:
b.size

8

#### 3-d array:

* combination of more 2-d arrays is 3-d array

In [81]:
c = np.array([[[1,2,3,4],[5,6,7,8]],[[5,6,7,8],[9,10,11,2]]])
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 5,  6,  7,  8],
        [ 9, 10, 11,  2]]])

In [80]:
c.ndim

3

In [82]:
len(c)

2

In [83]:
c.size

16

In [89]:
### Mutli Dimensional array:

d = np.array([1,2,3,4],ndmin = 32)

In [90]:
d

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2,
                                      3, 4]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [91]:
d.ndim

32

### Accessing elements from the array:


In [92]:
### 1-d array:

### list indexing and slicing can be applied to 1-d array

a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
a[-1]

10

In [94]:
a[0]

1

In [95]:
a[3:6]

array([4, 5, 6])

In [96]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [102]:
# 2-d array:

b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [98]:
b[0]

array([1, 2, 3, 4])

In [99]:
b[0][2]

3

In [101]:
b[0,2]  ### row index,element index

3

In [103]:
b[-1,-1]

8

In [104]:
b[0,-2:]

array([3, 4])

In [105]:
b[:,-2:]

array([[3, 4],
       [7, 8]])

In [106]:
### 3-d array:
c


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 5,  6,  7,  8],
        [ 9, 10, 11,  2]]])

In [107]:
c[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [108]:
c[0,0]

array([1, 2, 3, 4])

In [109]:
c[0,0,0]

1

In [110]:
c[:,:,-1]

array([[4, 8],
       [8, 2]])

### shape of the arrays:


In [111]:
## 1-d array:

a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
a.shape

(10,)

In [114]:
# 2-d array

b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [115]:
b.shape

(2, 4)

In [116]:
### 3-d array

c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 5,  6,  7,  8],
        [ 9, 10, 11,  2]]])

In [117]:
c.shape

(2, 2, 4)

### Reshaping of the arrays:

* giving the new shape to the array.

In [126]:
a = np.append(a,[12,11])

In [119]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [121]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [122]:
a.reshape(1,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [127]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 11])

In [128]:
a.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 12, 11]]])

In [129]:
a.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [12, 11]])

In [130]:
a.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 12, 11]])

In [132]:
a.reshape(2,-1,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 12, 11]]])

### Iterations of the arrays:

In [134]:
##  1-d array
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 11])

In [135]:
for i in a:
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 10 12 11 

In [136]:
### 2-d array:

b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [138]:
for i in b:
    for j in i:
        print(j,end =" ")

1 2 3 4 5 6 7 8 

In [139]:
### 3-d array:
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 5,  6,  7,  8],
        [ 9, 10, 11,  2]]])

In [141]:
for i in c:
    for j in i:
        for k in j:
            print(k,end = " ")

1 2 3 4 5 6 7 8 5 6 7 8 9 10 11 2 

### method for iterating the array elements:

np.nditer()


In [143]:
for i in np.nditer(c):
    print(i,end =  " ")

1 2 3 4 5 6 7 8 5 6 7 8 9 10 11 2 

### Joining of arrays:



In [144]:
## 1-d array

a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 4, 5, 6, 7])

In [145]:
### 2-d array:

d = a.reshape(2,2)
e = b.reshape(2,2)
c = np.concatenate((d,e))
c

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [147]:
## 3-d array:

d = a.reshape(2,1,2)
e = b.reshape(2,1,2)
c = np.concatenate((d,e))
c

array([[[1, 2]],

       [[3, 4]],

       [[4, 5]],

       [[6, 7]]])

###### to concatenate any two arrays the shape and dimension should be same.

### stastical and Mathematical operations on arrays:


In [152]:
a = a.reshape(2,2)
a


array([[1, 2],
       [3, 4]])

In [153]:
np.min(a)

1

In [154]:
np.max(a)

4

In [155]:
np.argmax(a)

3

In [158]:
np.argmin(a)

0

In [159]:
a.mean()

2.5

In [160]:
a

array([[1, 2],
       [3, 4]])

In [161]:
a.var()

1.25

In [163]:
np.median(a)

2.5

In [165]:
np.average(a)

2.5

In [166]:
np.std(a)

1.118033988749895

In [167]:
np.sum(a)

10

In [169]:
np.min(a,1)  ### 1-- row

array([1, 3])

In [171]:
np.min(a,0) ### 0-- column

array([1, 2])

In [172]:
np.argmax(a,1)

array([1, 1], dtype=int64)

### stacking:

* organising/arranging all the elements in a proper order.
* vertical
* horizontal

In [173]:
a

array([[1, 2],
       [3, 4]])

In [174]:
np.hstack(a)

array([1, 2, 3, 4])

In [175]:
np.vstack(a)

array([[1, 2],
       [3, 4]])

In [176]:
b = np.array(([[5,6],[7,8]]))

In [177]:
b

array([[5, 6],
       [7, 8]])

In [178]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [179]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [180]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [181]:
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [182]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [184]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [185]:
np.tan(a)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [186]:
np.log(a)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [187]:
np.log2(a)

array([[0.       , 1.       ],
       [1.5849625, 2.       ]])

In [188]:
np.remainder(a,4)

array([[1, 2],
       [3, 0]], dtype=int32)

In [189]:
np.degrees(a)

array([[ 57.29577951, 114.59155903],
       [171.88733854, 229.18311805]])

In [190]:
np.diff(a)

array([[1],
       [1]])

In [192]:
np.ediff1d(a)

array([1, 1, 1])

In [193]:
np.i0(a)

array([[ 1,  2],
       [ 4, 11]])

In [194]:
np.mod(a,3)

array([[1, 2],
       [0, 1]], dtype=int32)

In [196]:
np.power(a,3)

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [198]:
np.reciprocal(a,dtype = float)

array([[1.        , 0.5       ],
       [0.33333333, 0.25      ]])

In [201]:
np.multiply(a,2)

array([[2, 4],
       [6, 8]])

In [202]:
np.divide(a,2)

array([[0.5, 1. ],
       [1.5, 2. ]])

In [203]:
np.real(a)

array([[1, 2],
       [3, 4]])

In [204]:
np.imag(a)

array([[0, 0],
       [0, 0]])

In [205]:
a = np.array([1+2j,2+3j])

In [206]:
np.imag(a)

array([2., 3.])

### Ravel and Flatten:

In [207]:
original = np.array([1,2,3,4])
rav = original.ravel()
rav

array([1, 2, 3, 4])

In [208]:
rav[0] = 10

In [209]:
rav

array([10,  2,  3,  4])

In [210]:
original

array([10,  2,  3,  4])

In [211]:
rav[0] = 1

In [212]:
rav

array([1, 2, 3, 4])

In [214]:
original

array([1, 2, 3, 4])

In [215]:
original

array([1, 2, 3, 4])

In [217]:
fla = original.flatten()
fla

array([1, 2, 3, 4])

In [218]:
fla[0] = 10

In [219]:
fla

array([10,  2,  3,  4])

In [220]:
original

array([1, 2, 3, 4])